dist: trusty
sudo: false

language: node_js

before_install:
  - npm install -g luamin
  - git checkout ./bin/travis-minify.sh
  - git checkout ./bin/travis-test.sh
after_success:
  - ./bin/travis-minify.sh
install:
  - ./bin/travis-test.sh
